<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <RootNamespace>RelaxKonOS.Example.Windows11DesktopShell</RootNamespace>
    <AssemblyName>RelaxKonOS.Example.Windows11DesktopShell</AssemblyName>
    <AvaloniaUseCompiledBindingsByDefault>false</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Framework\RelaxKonOS.Shell\RelaxKonOS.Shell.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="Localization\*.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
