"""Mirrors the desktop client's icon assets into the Android app's resources.

The Android client does not draw an icon set of its own: it shows the same artwork the desktop
client ships, so a user moving between the two sees one product. The desktop assets are the source
of truth; this script derives the Android copies and is the only supported way to change them.

Source                                        Destination
  Assets/AppIcons/<name>.png                    res/drawable-nodpi/ic_app_<name>.png
  Assets/Icons/Explorer/<name>.png              res/drawable-nodpi/ic_sys_<name with '-' as '_'>.png
  Assets/RelaxKonOS-client-icon.png             res/drawable-nodpi/ic_app_brand.png
  Assets/RelaxKonOS-client-icon.png             the launcher icon (see below)

Android resource names must be lowercase and may contain neither '-' nor a second '.', which is why
the derived names differ from the desktop file names. `ui/icons/DesktopIcons.kt` is the single place
that maps a meaning onto one of these resources.

In-app icons are re-encoded at 128 px square. `drawable-nodpi` carries no density, so the largest
slot in the app (32dp, i.e. 128 px on an xxxhdpi screen) still samples at 1:1; the 192 px originals
would add roughly two megabytes for pixels no screen can show.

The launcher icon cannot be a single bitmap: a launcher draws it at a size this script cannot know,
and from API 26 it masks the artwork into the shape the user picked. So the mark is derived per
density into `res/mipmap-*dpi/`, plus an adaptive icon (`res/mipmap-anydpi-v26/`) whose background
is the gradient the app itself paints under every screen. The mark is drawn on transparency in the
desktop file — the desktop puts it on that same light surface, in the window title bar and the
sign-in banner — so the launcher gets the identical treatment rather than a second brand colour.

Run with any Python 3 interpreter plus Pillow:

    python Tools/Mobile/sync-desktop-icons.py            # rewrite the derived resources
    python Tools/Mobile/sync-desktop-icons.py --check    # fail if they are out of date
"""
from __future__ import annotations

import argparse
import io
import pathlib
import sys

from PIL import Image, ImageDraw

REPO = pathlib.Path(__file__).resolve().parents[2]
DESKTOP_ASSETS = REPO / "Client" / "RelaxKonOS.Client" / "Assets"
ANDROID_RES = REPO / "Client" / "RelaxKonOS.Client.Android" / "app" / "src" / "main" / "res"
TARGET = ANDROID_RES / "drawable-nodpi"

SIZE = 128

# `debug-grid.png` is a 2048x768 sprite sheet kept beside the app icons, not an icon itself.
SKIP = {"debug-grid"}

# The product mark, the one desktop asset that also has to become the launcher icon.
BRAND = DESKTOP_ASSETS / "RelaxKonOS-client-icon.png"

# The backdrop gradient from `ui/theme/Palette.kt` (RelaxKonLightColors.backdropStart/End), the
# surface the app paints under every screen and the one the desktop draws the mark on.
BACKDROP_START = (0xF7, 0xF9, 0xFE)
BACKDROP_END = (0xE7, 0xEE, 0xFA)

# Launcher densities: the legacy tile a pre-API-26 launcher shows, and the 108dp adaptive canvas.
# 108dp is the platform's number, so these are 1x/1.5x/2x/3x/4x of it.
DENSITIES = {
    "mdpi": (48, 108),
    "hdpi": (72, 162),
    "xhdpi": (96, 216),
    "xxhdpi": (144, 324),
    "xxxhdpi": (192, 432),
}

# Share of the canvas the mark's longest side occupies. The mark's ink reaches 0.67 of that side
# from its centre, so each fraction is really a statement about which mask has to contain it:
#   adaptive  108dp canvas, 72dp mask  -> 0.48 leaves the ink ~1dp inside a circular mask
#   legacy square  the tile is the icon, so the mark can fill it further
#   legacy round   a circle loses the corners a square keeps, so it needs a little more than the
#                  square tile does to read as equally full
ADAPTIVE_MARK = 0.48
LEGACY_MARK = 0.70
ROUND_MARK = 0.68

# The corner radius of a pre-API-26 tile, as a share of its size.
LEGACY_RADIUS = 0.22


def hex_colour(rgb: tuple[int, int, int]) -> str:
    return "#%02X%02X%02X" % rgb


ADAPTIVE_ICON = b"""<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by Tools/Mobile/sync-desktop-icons.py from the desktop product mark. -->
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
    <background android:drawable="@drawable/ic_launcher_background" />
    <foreground android:drawable="@mipmap/ic_launcher_foreground" />
</adaptive-icon>
"""

BACKGROUND_SHAPE = (
    """<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by Tools/Mobile/sync-desktop-icons.py; the app's own backdrop gradient. -->
<shape xmlns:android="http://schemas.android.com/apk/res/android" android:shape="rectangle">
    <gradient
        android:angle="270"
        android:startColor="%s"
        android:endColor="%s"
        android:type="linear" />
</shape>
"""
    % (hex_colour(BACKDROP_START), hex_colour(BACKDROP_END))
).encode()

# Every file this script owns, as (directory, glob). Anything matching one of these but not
# produced below was removed upstream and is deleted.
OWNED = (
    (TARGET, "ic_*.png"),
    (ANDROID_RES, "mipmap-*/ic_launcher*.png"),
    (ANDROID_RES, "mipmap-*/ic_launcher*.xml"),
    (ANDROID_RES, "drawable/ic_launcher_background.xml"),
)


def sources() -> list[tuple[pathlib.Path, str]]:
    """Every (source file, Android resource name) pair mirrored into `drawable-nodpi`."""
    found: list[tuple[pathlib.Path, str]] = [
        # The product mark the desktop uses for its window, tray and taskbar entries.
        (BRAND, "ic_app_brand"),
    ]

    for path in sorted((DESKTOP_ASSETS / "AppIcons").glob("*.png")):
        if path.stem in SKIP:
            continue
        found.append((path, f"ic_app_{path.stem.replace('-', '_')}"))

    for path in sorted((DESKTOP_ASSETS / "Icons" / "Explorer").glob("*.png")):
        found.append((path, f"ic_sys_{path.stem.replace('-', '_')}"))

    missing = [str(path) for path, _ in found if not path.exists()]
    if missing:
        raise SystemExit("missing source icons: " + ", ".join(missing))
    return found


def png(image: Image.Image) -> bytes:
    buffer = io.BytesIO()
    image.save(buffer, format="PNG", optimize=True)
    return buffer.getvalue()


def encode(source: pathlib.Path) -> bytes:
    """The exact bytes the `drawable-nodpi` copy must hold for [source]."""
    image = Image.open(source).convert("RGBA")
    if image.width != image.height:
        raise SystemExit(f"{source.name}: expected a square canvas, got {image.width}x{image.height}")
    return png(image.resize((SIZE, SIZE), Image.LANCZOS))


def mark() -> Image.Image:
    """The product mark alone, cropped to its ink.

    The desktop file is the mark drawn on transparency with a margin of empty pixels; every
    launcher layer sizes the mark against a canvas of its own, so the margin has to go first.
    """
    image = Image.open(BRAND).convert("RGBA")
    bounds = image.split()[3].getbbox()
    if bounds is None:
        raise SystemExit(f"{BRAND.name}: the brand mark is fully transparent")
    return image.crop(bounds)


def fitted(source: Image.Image, extent: int) -> Image.Image:
    """[source] scaled so its longest side measures [extent] pixels."""
    ratio = extent / max(source.width, source.height)
    size = (max(1, round(source.width * ratio)), max(1, round(source.height * ratio)))
    return source.resize(size, Image.LANCZOS)


def place(canvas: Image.Image, stamp: Image.Image) -> Image.Image:
    """[stamp] centred on [canvas]. Compositing rather than pasting keeps soft edges soft."""
    layer = Image.new("RGBA", canvas.size, (0, 0, 0, 0))
    layer.paste(stamp, ((canvas.width - stamp.width) // 2, (canvas.height - stamp.height) // 2))
    return Image.alpha_composite(canvas, layer)


def backdrop(size: int) -> Image.Image:
    """The app's backdrop gradient as a square tile, darkest at the bottom like the app's."""
    column = Image.new("RGB", (1, size))
    for y in range(size):
        ratio = y / (size - 1) if size > 1 else 0
        column.putpixel(
            (0, y),
            tuple(round(start + (end - start) * ratio) for start, end in zip(BACKDROP_START, BACKDROP_END)),
        )
    return column.resize((size, size), Image.NEAREST).convert("RGBA")


def tile_mask(size: int, radius: float | None) -> Image.Image:
    """An opaque rounded square, or a circle when [radius] is `None`.

    A legacy launcher icon is the whole tile — shape included — so the edge is a bitmap edge
    rather than a platform mask, and drawing it supersampled keeps it as smooth as the mark.
    """
    scale = 4
    mask = Image.new("L", (size * scale, size * scale), 0)
    box = (0, 0, size * scale - 1, size * scale - 1)
    draw = ImageDraw.Draw(mask)
    if radius is None:
        draw.ellipse(box, fill=255)
    else:
        draw.rounded_rectangle(box, radius=round(size * scale * radius), fill=255)
    return mask.resize((size, size), Image.LANCZOS)


def launcher_files() -> dict[pathlib.Path, bytes]:
    """Every launcher icon file, keyed by the path it has to live at."""
    source = mark()
    files: dict[pathlib.Path, bytes] = {}

    for density, (tile_px, adaptive_px) in DENSITIES.items():
        directory = ANDROID_RES / f"mipmap-{density}"
        for name, radius, fraction in (
            ("ic_launcher", LEGACY_RADIUS, LEGACY_MARK),
            ("ic_launcher_round", None, ROUND_MARK),
        ):
            tile = backdrop(tile_px)
            tile.putalpha(tile_mask(tile_px, radius))
            files[directory / f"{name}.png"] = png(place(tile, fitted(source, round(tile_px * fraction))))

        # The adaptive icon's own foreground: the mark alone, the launcher's mask supplying the shape.
        foreground = Image.new("RGBA", (adaptive_px, adaptive_px), (0, 0, 0, 0))
        files[directory / "ic_launcher_foreground.png"] = png(
            place(foreground, fitted(source, round(adaptive_px * ADAPTIVE_MARK)))
        )

    for name in ("ic_launcher", "ic_launcher_round"):
        files[ANDROID_RES / "mipmap-anydpi-v26" / f"{name}.xml"] = ADAPTIVE_ICON
    files[ANDROID_RES / "drawable" / "ic_launcher_background.xml"] = BACKGROUND_SHAPE
    return files


def derived() -> dict[pathlib.Path, bytes]:
    """Every file this script owns, keyed by path."""
    files = {TARGET / f"{name}.png": encode(source) for source, name in sources()}
    files.update(launcher_files())
    return files


def orphans(produced: dict[pathlib.Path, bytes]) -> list[pathlib.Path]:
    """Owned files that nothing here produces any more, i.e. artwork removed upstream."""
    found: list[pathlib.Path] = []
    for directory, pattern in OWNED:
        if not directory.exists():
            continue
        found.extend(path for path in directory.glob(pattern) if path not in produced)
    return sorted(found)


def main() -> int:
    parser = argparse.ArgumentParser(description="Mirror desktop icons into the Android app.")
    parser.add_argument("--check", action="store_true", help="report drift instead of writing files")
    arguments = parser.parse_args()

    files = derived()
    stale = sorted(
        path
        for path, payload in files.items()
        if not path.exists() or path.read_bytes() != payload
    )
    removed = orphans(files)

    if arguments.check:
        for path in stale:
            print(f"out of date: {path.relative_to(REPO)}")
        for path in removed:
            print(f"no longer produced: {path.relative_to(REPO)}")
        if stale or removed:
            return 1
        print(f"{len(files)} icons are up to date")
        return 0

    for path in stale:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(files[path])
    for path in removed:
        path.unlink()
        print(f"removed: {path.relative_to(REPO)}")
    print(f"wrote {len(stale)} of {len(files)} icons into {ANDROID_RES.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())