<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>latest</LangVersion>
        <RootNamespace>RelaxKonOS.WindowManager</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia" />
        <PackageReference Include="CommunityToolkit.Mvvm" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\RelaxKonOS.Core\RelaxKonOS.Core.csproj" />
        <ProjectReference Include="..\RelaxKonOS.UI\RelaxKonOS.UI.csproj" />
    </ItemGroup>

</Project>
