<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../../../RelaxKonOS.Server/Settings/WorkspacePreferencesValidator.cs" Link="WorkspacePreferencesValidator.cs" />
    <ProjectReference Include="../../../Client/RelaxKonOS.Client/RelaxKonOS.Client.csproj" />
    <PackageReference Include="Avalonia.Desktop" />
  </ItemGroup>
</Project>
